FROM 192.168.18.250:5002/ufleet-build/python:env-base

MAINTAINER youruncloud

RUN pip install --no-cache-dir paramiko==2.1.2 \
	txsockjs==1.2.2 \
	pykube==0.15.0 \
	requests==2.17.3 \
	etcd3==0.6.2
	gevent==1.2.2


